# Default values for tensorio-models.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

deployment:
  replicas: 1
  repository: tensorio/repository
  tag: latest
  pullPolicy: IfNotPresent
  backend: memory

service:
  type: ClusterIP
  grpcPort: 7316
  restPort: 7317
  hostname: tensorio-models.default
